server:
  port: 8082

spring:
  application:
    name: monicar-track-alert

  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/monicar_db
    username: local_user
    password: local_password