server:
  port: 8090

spring:
  application:
    name: monicar-emulator

logging:
  level:
    org:
      apache:
        hc:
          client5:
            http=DEBUG:

api:
  protocol: http
  host: localhost
  port: 8082
  server: event-hub